test: print guard

diff --git a/packages/copilot-cli/package.yaml b/packages/copilot-cli/package.yaml
--- a/packages/copilot-cli/package.yaml
+++ b/packages/copilot-cli/package.yaml
@@ -28,5 +28,9 @@ init_cmds:
     cp -f node_modules/@devm33/node-pty/build/Release/pty.node "$COPILOT_PTY_DIR"
 
     # Remove prebuilt GLIBC 2.28 copilot binary
+    if [ ! -d "$HOME/.local/share/personal-setup/node_modules/@github/copilot-linux-x64" ]; then
+      echo "Cannot find $HOME/.local/share/personal-setup/node_modules/@github/copilot-linux-x64" > /dev/stderr
+      exit 1
+    fi
     rm -rf $HOME/.local/share/personal-setup/node_modules/.bin/copilot-linux-x64
     rm -rf $HOME/.local/share/personal-setup/node_modules/@github/copilot-linux-x64
